contacts/urls.py
from django.conf.urls import patterns, include, url
from contacts.views import ListContactView, CreateContactView, EditContactAddressView
from contacts.views import DeleteContactView, UpdateContactView, ContactView

urlpatterns = patterns('',
    url(r'^$', ListContactView.as_view(), name='contacts-list',),
    url(r'^new/$', CreateContactView.as_view(), name='contacts-new',),
    url(r'^edit/(?P<pk>\d+)/$', UpdateContactView.as_view(), name='contacts-edit',),
    url(r'^delete/(?P<pk>\d+)/$', DeleteContactView.as_view(), name='contacts-delete',),
    url(r'^(?P<pk>\d+)/$', ContactView.as_view(), name='contacts-view',),
    url(r'^edit/(?P<pk>\d+)/addresses/$', EditContactAddressView.as_view(),
        name='contacts-edit-addresses',),
)

test_app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import contacts

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'test_app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
    url(r'^', include('contacts.urls')),
)

urlpatterns += staticfiles_urlpatterns()

contacts/models.py
#-*- encoding:utf-8 -*-

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Contact(models.Model):

    first_name = models.CharField(max_length=255,)
    last_name = models.CharField(max_length=255,)
    email = models.EmailField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __unicode__(self):
        return ' '.join([self.first_name, self.last_name,])
        
    def get_absolute_url(self):
        return reverse('contacts-view', kwargs={'pk': self.id})


class Address(models.Model):
    contact = models.ForeignKey(Contact)
    address_type = models.CharField(max_length=10,)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255,)
    state = models.CharField(max_length=2,)
    postal_code = models.CharField(max_length=20,)

    def __unicode__(self):
        return self.address

    class Meta:
        unique_together = ('contact', 'address_type',)
        
    

contacts/forms.py
# -*- encoding:utf-8 -*-

from django import forms
from django.core.exceptions import ValidationError
from contacts.models import Contact, Address
from django.forms.models import inlineformset_factory

ContactAddressFormSet = inlineformset_factory(Contact, Address,)


class ContactForm(forms.ModelForm):
    confirm_email = forms.EmailField(label="Confirm email", required=True,)
    
    class Meta:
        model = Contact
    
    def __init__(self, *args, **kwargs):
        if kwargs.get('instance'):
            email = kwargs['instance'].email
            kwargs.setdefault('initial', {})['confirm_email'] = email
    
        return super(ContactForm, self).__init__(*args, **kwargs)
        
    def clean(self):
        if (self.cleaned_data.get('email') != self.cleaned_data.get('confirm_email')):
            raise ValidationError("Email addresses must match.")
        
        return self.cleaned_data
            

contacts/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
import forms
from django.core.urlresolvers import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from contacts.models import Contact
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


class LoggedInMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)


class ListContactView(LoggedInMixin, ListView):
    model = Contact
    template_name = 'contact_list.html'
    
    def get_queryset(self):
        contact_list = Contact.objects.filter(owner=self.request.user)
        
        paginator = Paginator(contact_list, 5)
        page = self.request.GET.get('page')
        
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            contacts = paginator.page(paginator.num_pages)
        return contacts
        

class CreateContactView(LoggedInMixin, CreateView):
    model = Contact
    template_name = 'edit_contact.html'
    form_class = forms.ContactForm
    
    def get_success_url(self, **kwargs):
        context = super(CreateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-new')
        return reverse('contacts-list')
        

class UpdateContactView(LoggedInMixin, UpdateView):
    model = Contact
    template_name = 'edit_contact.html'
    form_class = forms.ContactForm
    
    def get_success_url(self, **kwargs):
        context = super(UpdateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-edit', kwargs={'pk': self.get_object().id})
        return reverse('contacts-list')


class DeleteContactView(LoggedInMixin, DeleteView):
    model = Contact
    template_name = 'delete_contact.html'

    def get_success_url(self):
        return reverse('contacts-list')


class EditContactAddressView(LoggedInMixin, UpdateView):
    model = Contact
    template_name = 'edit_addresses.html'
    form_class = forms.ContactAddressFormSet

    def get_success_url(self):
        # redirect to the Contact view.
        return self.get_object().get_absolute_url()


class ContactView(LoggedInMixin, DetailView):
    model = Contact
    template_name = 'contact.html'

contacts/templates/base.html
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    </head>
    <body style="padding-top:60px;">
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
        
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" style="color:white">Address book</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li> <a href="{% url "contacts-list" %}">Contact</a></li>
            <li> <a href="{% url "contacts-new" %}">Add contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
                <div style="color:white">
                    {{ user }}
                    {% if user.is_anonymous %}
                        <a href="{% url 'django.contrib.auth.views.login' %}">login</a>
                    {% else %}
                        <a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
                    {% endif %}
                </div>
            </li>
          </ul>
        </div>
        
        </div>
    </nav>
    
    <div>
        <p>login: user, password: password </p> 
    </div>
        
    <div class="row-fluid">
        <div class="col-xs-2 col-sm-2 col-md-2"></div>
        
        <div class="col-xs-8 col-sm-8 col-md-8">
            {% block content %}
            {% endblock %}
        </div>
        
        <div class="col-xs-2 col-sm-2 col-md-2"></div>
    </div>    
    
    
    <footer class="navbar navbar-default navbar-fixed-bottom">
        <div class="container" >
        <div class="navbar-inner navbar-content-center">
            <p class="text-muted text-center">2015</p>
        </div>
        </div>
    </footer>
    
        
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    
    </body>
</html>

contacts/templates/contact.html
{% extends "base.html" %}

{% block content %}

<h1>{{ contact }}</h1>

<p>Email: {{ contact.email }}</p>

<a class="btn btn-primary" href="{% url "contacts-edit-addresses" pk=contact.id %}">Edit addresses for {{ contact.first_name }} </a>
<br><br>
<ul>
{% for address in contact.address_set.all %}
    <li>{{ address.address }}<br/>
        {{ address.city }} {{ address.state }}<br/>
        {{ address.postal_code }}
    </li>
{% endfor %}
</ul>

{% endblock %}

contacts/templates/contact_list.html
{% extends "base.html" %}

{% block content %}
<h1>Contacts</h1>

<ul>
    <!--{% for contact in object_list %}
    <li class="contact">
        <a href="{{ contact.get_absolute_url }}">{{ contact }}</a>
        (<a href="{% url "contacts-edit" pk=contact.id %}">edit</a>)
    </li>
    {% endfor %}-->
    
    {% for contact in object_list %}
        <li class="contact">
        <a href="{{ contact.get_absolute_url }}">{{ contact }}</a>
        (<a href="{% url "contacts-edit" pk=contact.id %}">edit</a>)
    </li>
    {% endfor %}
    
    <div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page={{ object_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
    
</ul>
{% endblock %}

contacts/templates/delete_contact.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Contact</h1>
<p>Are you sure you want to delete the contact {{ contact }}?</p>
<form action="{% url "contacts-delete" pk=contact.id %}" method="POST">
{% csrf_token %}
<input class="btn btn-danger" type="submit" value="Yes, delete." />
<a class="btn btn-default" href="{% url "contacts-list" %}" >No, cancel.</a>
</form>

{% endblock %}

contacts/templates/edit_addresses.html
{% extends "base.html" %}
{% block content %}

<h1>Edit Addresses</h1>

<p>Editing addresses for {{ contact }}</p>
<form action="{% url "contacts-edit-addresses" pk=contact.id %}" method="POST">
    {% csrf_token %}
    {{ form.management_form }}
    {% for address_form in form %}
        <ul>
            {{ address_form.as_ul }}
        </ul>
    {% endfor %}
    <input type="submit" value="Save" />
</form>

{% endblock %}

contacts/templates/edit_contact.html
{% extends "base.html" %}

{% block content %}

{% if contact.id %}
  <h1>Edit Contact</h1>
{% else %}
  <h1>Add Contact</h1>
{% endif %}

<a class="btn btn-default" href="{% url "contacts-list" %}">back to list</a>
<br><br>
<form action="{{ action }}" method="POST">
      {% csrf_token %}
      
      {% if form.non_field_errors %}
      <ul>
        {% for error in form.non_field_errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      
      {% for field in form %}
        <div id="{{ field.auto_id }}_container">
          {{ field.help_text }}
          <div>
            {{ field.label_tag }} {{ field }}
          </div>
          <div id="{{ field.auto_id }}_errors">
            {{ field.errors }}
          </div>
        </div>
      {% endfor %}
      <br>
      <input class="btn btn-success" id="save_contact" type="submit" value="Save" />
      {% if contact.id %}
        <a class="btn btn-danger" href="{% url "contacts-delete" pk=contact.id %}">Delete</a>
      {% endif %}
</form>

{% endblock %}